package com.archify.generator;

import org.junit.jupiter.api.Test;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class ArchifyGeneratorFacadeJdbcRecipeTest {

    private final ArchifyGeneratorFacade facade = new ArchifyGeneratorFacade();

    @Test
    void jdbcTemplateH2RecipeGeneratesGenericJdbcProject() throws IOException {
        Map<String, String> files = unzip(facade.generateZip("rest-jdbc-template-h2", sampleConfig()));

        String root = "archify-project/inventory-service/";
        assertTrue(files.containsKey(root + "pom.xml"));
        assertTrue(files.containsKey(root + "src/main/resources/schema.sql"));
        assertTrue(files.containsKey(root + "src/main/java/com/archify/inventoryservice/entity/Invoice.java"));
        assertTrue(files.containsKey(root + "src/main/java/com/archify/inventoryservice/repository/InvoiceRepository.java"));

        assertContains(files.get(root + "pom.xml"), "spring-boot-starter-jdbc");
        assertContains(files.get(root + "pom.xml"), "<artifactId>h2</artifactId>");
        assertContains(files.get(root + "src/main/resources/application.yml"), "jdbc:h2:mem:${spring.application.name}");
        assertContains(files.get(root + "src/main/resources/application.yml"), "init:");
        assertContains(files.get(root + "src/main/resources/schema.sql"), "CREATE TABLE IF NOT EXISTS invoices");
        assertContains(files.get(root + "src/main/resources/schema.sql"), "amount DECIMAL(19,2) NOT NULL");
        assertContains(files.get(root + "src/main/resources/schema.sql"), "active BOOLEAN NOT NULL");
        assertContains(files.get(root + "src/main/java/com/archify/inventoryservice/repository/InvoiceRepository.java"), "JdbcTemplate");
        assertContains(files.get(root + "src/main/java/com/archify/inventoryservice/repository/InvoiceRepository.java"), "INSERT INTO invoices");
        assertFalse(files.get(root + "src/main/java/com/archify/inventoryservice/entity/Invoice.java").contains("Trade"));
    }

    @Test
    void jdbcTemplatePostgresRecipeGeneratesPostgresJdbcProject() throws IOException {
        Map<String, String> files = unzip(facade.generateZip("rest-jdbc-template-postgres", sampleConfig()));

        String root = "archify-project/inventory-service/";
        assertContains(files.get(root + "pom.xml"), "spring-boot-starter-jdbc");
        assertContains(files.get(root + "pom.xml"), "<artifactId>postgresql</artifactId>");
        assertContains(files.get(root + "src/main/resources/application.yml"), "jdbc:postgresql://localhost:5432/${spring.application.name}");
        assertContains(files.get(root + "src/main/resources/schema.sql"), "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
        assertContains(files.get("archify-project/README.md"), "rest-jdbc-template-postgres");
    }

    private Map<String, Object> sampleConfig() {
        Map<String, Object> config = new HashMap<>();
        config.put("serviceName", "inventory-service");
        config.put("entities", List.of(
                Map.of(
                        "name", "Invoice",
                        "fields", List.of(
                                Map.of("name", "amount", "type", "bigdecimal"),
                                Map.of("name", "active", "type", "boolean")
                        )
                )
        ));
        return config;
    }

    private Map<String, String> unzip(byte[] content) throws IOException {
        Map<String, String> files = new HashMap<>();
        try (ZipInputStream inputStream = new ZipInputStream(new ByteArrayInputStream(content), StandardCharsets.UTF_8)) {
            ZipEntry entry;
            while ((entry = inputStream.getNextEntry()) != null) {
                if (!entry.isDirectory()) {
                    files.put(entry.getName(), new String(inputStream.readAllBytes(), StandardCharsets.UTF_8));
                }
            }
        }
        return files;
    }

    private void assertContains(String value, String expected) {
        assertTrue(value.contains(expected), () -> "Expected to find '" + expected + "' in:\n" + value);
    }
}
